deploy:
  name: adisyo-landing
  replicas: 1
  port: 80
  image: adisyo/adisyo-landing
  tag: latest
  registry: adisyoacr.azurecr.io/
  minReadySeconds: 10
  resources:
    enabled: true
    requestCpu: 50m
    requestMemory: 100Mi
    limitCpu: 200m
    limitMemory: 300Mi
  nodeSelector:
    enabled: true
    InorNotIn: NotIn
  newrelic:
    enabled: false
svc:
  enabled: true
  name: adisyo-landing
  port: 80
svcMonitor:
  enabled: false
hpa:
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 60
    # targetMemoryUtilizationPercentage: 90
probe:
  enabled: true
  failureThreshold: 1
  periodSeconds: 10
  timeoutSeconds: 20
  initialDelaySeconds: 70
  pathreadiness: /health
  pathliveness: /health
  port: 5000
ingress:
  enabled: true
  className: nginx
  hosts:
    - landing.adisyo.com
    - adisyo.com
  request:
    size: 100m
env:
  
