{{- if .Values.svcMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.svc.name }}
  labels:
    adisyo-monitoring: adisyo-prometheus-exporter
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - port: http
    interval: "30s"
    scrapeTimeout: "10s"
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.svc.name }}
{{- end }}