deploy:
  name: adisyo-coreapi
  replicas: 1
  port: 5000
  image: adisyo/adisyo-coreapi
  tag: latest
  registry: adisyoacr.azurecr.io/
  minReadySeconds: 60
  resources:
    enabled: true
    requestCpu: 600m
    requestMemory: 1800Mi
    limitCpu: 1000m
    limitMemory: 2400Mi
  nodeSelector:
    enabled: true
    InorNotIn: NotIn
  newrelic:
    enabled: false
svc:
  enabled: true
  name: adisyo-coreapi
  port: 80
svcMonitor:
  enabled: false
hpa:
  autoscaling:
    enabled: true
    minReplicas: 4
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
    # targetMemoryUtilizationPercentage: 90
probe:
  enabled: true
  failureThreshold: 1
  periodSeconds: 10
  timeoutSeconds: 20
  initialDelaySeconds: 70
  pathreadiness: /health
  pathliveness: /health
  port: 5000
ingress:
  enabled: true
  className: nginx
  hosts:
    - coreapi-a.adisyo.com
    - api.adisyo.com
    - int.adisyo.com
    - ext.adisyo.com
    - ord.adisyo.com
    - awsapi.adisyo.com
  request:
    size: 100m
env:
  ConnectionStrings__lokantapp: "Server=tcp:adisyo.database.windows.net,1433;Initial Catalog=adisyo;Persist Security Info=False;User ID=produser;Password=2PXcGZY_SO7CxaCi;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=15;Min Pool Size=15; Max Pool Size=40;"
  ConnectionStrings__lokantappro: "Server=tcp:adisyo.database.windows.net,1433;ApplicationIntent=ReadOnly;Initial Catalog=adisyo;Persist Security Info=False;User ID=produser;Password=2PXcGZY_SO7CxaCi;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=15;"
  AppSettings__HubUrl: "http://adisyo-hub.prod-a.svc.cluster.local./"
